services:
  mysql:
    image: mysql:8.0
    container_name: music_streaming_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: music_streaming
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data:
